# Generated by Django 6.0.2 on 2026-02-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('SAUDE', 'Saúde'), ('FINANCAS', 'Finanças'), ('RECEITAS', 'Receitas'), ('MUNDO', 'Mundo'), ('GERAL', 'Geral')], default='GERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
    ]
