# Generated by Django 6.0.2 on 2026-02-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_noticia_categoria_noticia_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='legenda_imagem',
            field=models.CharField(blank=True, help_text='Opcional: Créditos da foto ou descrição curta', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='Opcional: Uma frase curta que complementa o título', max_length=300, null=True),
        ),
    ]
